apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknadsmottaker
  namespace: {{namespace}}
  labels:
    team: team-soknad
spec:
  image: {{image}}
  port: 8090
  liveness:
    path: /health/isAlive
    initialDelay: 20
    failureThreshold: 10
    timeout: 1
  readiness:
    path: /health/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingress}}
    - "{{this}}"
  {{/each}}
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: {{service-user-path}}
      - mountPath: /secrets/innsending-data
        kvPath: secret/team-soknad/innsending/basicauth
  kafka:
    pool: {{ kafka-pool }}
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: {{kafka-bootstrap-servers}}
    - name: SCHEMA_REGISTRY_URL
      value: {{schema-registry-url}}
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: SPRING_PROFILES_ACTIVE
      value: {{profile}}
    - name: KAFKA_MAIN_TOPIC
      value: {{kafka-main-topic}}
    - name: KAFKA_METRICS_TOPIC
      value: {{kafka-metrics-topic}}
    - name: KAFKA_BRUKERNOTIFIKASJON_DONE_TOPIC
      value: {{kafka-brukernotifikasjon-done-topic}}
    - name: KAFKA_BRUKERNOTIFIKASJON_BESKJED_TOPIC
      value: {{kafka-brukernotifikasjon-beskjed-topic}}
    - name: KAFKA_BRUKERNOTIFIKASJON_OPPGAVE_TOPIC
      value: {{kafka-brukernotifikasjon-oppgave-topic}}
